[package]
name = "bess-rs"
version = "0.1.0"
authors = ["@eshikafe"]
description = "BESS implementation in Rust"
edition = "2021"

[[bin]]
name = "bessd"
path = "core/main.rs"

[dependencies]
nix = {version = "0.24.2", features = ["user"]}
log = "0.4.17"
env_logger = "0.9.0"
libc = "0.2"
gflags = "0.3.11"
clap = "3.2.12"
macaddr = "1.0.1"