[package]
name = "bessctl"
version = "0.1.0"
description = "BESS daemon controller"
edition = "2021"

[dependencies]
log = "0.4.17"
env_logger = "0.9.0"
clap = {version = "3.2.12", features = ["derive"]}
macaddr = "1.0.1"